<div class="menu-wrapper">
    <div class="menu-item"><a href="index.php" class="btn">Home</a></div>
    <div class="menu-item"><a href="about.php" class="btn">About</a></div>
    <div class="menu-item"><a href="jobs.php" class="btn">Jobs</a></div>
    <div class="menu-item"><a href="apply.php" class="btn">Apply </a></div>
    <div class="menu-item"><a href="enhancements.php" class="btn">Enhancement</a></div>
    <div class="menu-item"><a href="phpenhancements.php" class="btn">PHP Enhancement</a></div>
    <div class="menu-item"><a href="manage.php" class="btn">EOI Management</a></div>
    <div class="menu-item"><a href="jobManage.php" class="btn">Job Management</a></div>
</div>